global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets:
          - "monitoring-node-exporter-server:9100"

  - job_name: "web"
    metrics_path: "/"
    static_configs:
      - targets:
          - "web-frontend-server:80"
